//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlijentFramework.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/Kupidon")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrojTelefonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GodineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrimioPorukuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrojTelefona {
            get {
                return this.BrojTelefonaField;
            }
            set {
                if ((object.ReferenceEquals(this.BrojTelefonaField, value) != true)) {
                    this.BrojTelefonaField = value;
                    this.RaisePropertyChanged("BrojTelefona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Godine {
            get {
                return this.GodineField;
            }
            set {
                if ((this.GodineField.Equals(value) != true)) {
                    this.GodineField = value;
                    this.RaisePropertyChanged("Godine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grad {
            get {
                return this.GradField;
            }
            set {
                if ((object.ReferenceEquals(this.GradField, value) != true)) {
                    this.GradField = value;
                    this.RaisePropertyChanged("Grad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrimioPoruku {
            get {
                return this.PrimioPorukuField;
            }
            set {
                if ((this.PrimioPorukuField.Equals(value) != true)) {
                    this.PrimioPorukuField = value;
                    this.RaisePropertyChanged("PrimioPoruku");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPub")]
    public interface IPub {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPub/sendLetters")]
        void sendLetters(string poruka);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPub/sendLetters")]
        System.Threading.Tasks.Task sendLettersAsync(string poruka);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPubChannel : KlijentFramework.ServiceReference1.IPub, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PubClient : System.ServiceModel.ClientBase<KlijentFramework.ServiceReference1.IPub>, KlijentFramework.ServiceReference1.IPub {
        
        public PubClient() {
        }
        
        public PubClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PubClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PubClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PubClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendLetters(string poruka) {
            base.Channel.sendLetters(poruka);
        }
        
        public System.Threading.Tasks.Task sendLettersAsync(string poruka) {
            return base.Channel.sendLettersAsync(poruka);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISub", CallbackContract=typeof(KlijentFramework.ServiceReference1.ISubCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISub {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISub/initSinglePerson")]
        void initSinglePerson(KlijentFramework.ServiceReference1.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISub/initSinglePerson")]
        System.Threading.Tasks.Task initSinglePersonAsync(KlijentFramework.ServiceReference1.Korisnik korisnik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISub/OnNotified")]
        void OnNotified(string message, KlijentFramework.ServiceReference1.Korisnik[] korisnici);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubChannel : KlijentFramework.ServiceReference1.ISub, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubClient : System.ServiceModel.DuplexClientBase<KlijentFramework.ServiceReference1.ISub>, KlijentFramework.ServiceReference1.ISub {
        
        public SubClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void initSinglePerson(KlijentFramework.ServiceReference1.Korisnik korisnik) {
            base.Channel.initSinglePerson(korisnik);
        }
        
        public System.Threading.Tasks.Task initSinglePersonAsync(KlijentFramework.ServiceReference1.Korisnik korisnik) {
            return base.Channel.initSinglePersonAsync(korisnik);
        }
    }
}
